project:
  type: website
  render:
    - index.md
    - Session_notebooks/*

website:
  title: "UQ Python User Group"
  sidebar:
    contents:
      - text: General information
        href: index.md
      - auto: Session_notebooks

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
