project:
  type: website
  render:
    - index.md
    - "Current notebooks/*"
    - "Archive - 2023/*"

website:
  title: "UQ Python User Group"
  sidebar:
    contents:
      - href: index.md 
        text: General information
      - auto: "Current notebooks"
      - auto: "Archive - 2023"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
